---

- name: Restart service
  ansible.builtin.systemd:
    state: restarted
    name: "{{ postgres_instance_name }}.service"
    daemon_reload: true
    enabled: true
  listen:
    - restart service
