#!/bin/bash
set -euo pipefail
for i in 2 3 4 5 6 7 8 9 10 11 12
    do
        if mountpoint -q "/boot/efi${i}" ; then
            grub-install --efi-directory="/boot/efi${i}" --bootloader-id="ubuntu${i}"
        fi
    done
exit 0
